### ISSUE TITLE
Error while loading wdm.h

### ISSUE THREAD

**Issue by ethergrouik** [matteyeux/binja-import-header#2]
Hello,
I have a problem while trying to load the wdm.h file.
Could you take a look at it please ?

Thank you in advance.
Ethergrouik

Binary Ninja: Version 3.0.3233 Personal (Build ID e250d0a3)

```
Traceback (most recent call last):
  File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 120, in _default_action
    action(view_obj)
  File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\community\plugins\matteyeux_binjaimportheader\__init__.py", line 15, in import_header
    types = binaryview.platform.parse_types_from_source_file(header.result)
  File "C:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\platform.py", line 482, in parse_types_from_source_file
    raise SyntaxError(error_str)
SyntaxError: C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/km/wdm.h:37: error: syntax error

```

**Comment by MultiTeemer** [comment]
Hello, I have the same problem.

**Comment by matteyeux** [comment]
Hello, sorry for late reply. 

This is a syntax error in the header. It's not related to this plugin. 
Btw if you update to latest Binja dev there is a native feature that replaces this plugin.
